[pool]
characters = [
	"Isaac",
	"Magdalene",
	"Cain",
	"Judas",
	"???",
	"Eve",
	"Samson",
	"Azazael",
	"Lazarus",
	"Eden",
	"Lost",
	"Lilith",
	"Keeper",
	"Apollyon",
	"Forgotten",
	"Behtany",
	"Jacob & Esau",
	"Tainted Isaac",
	"Tainted Magdalene",
	"Tainted Cain",
	"Tainted Judas",
	"Tainted ???",
	"Tainted Eve",
	"Tainted Samson",
	"Tainted Azazael",
	"Tainted Lazarus",
	"Tainted Eden",
	"Tainted Lost",
	"Tainted Lilith",
	"Tainted Keeper",
	"Tainted Apollyon",
	"Tainted Forgotten",
	"Tainted Behtany",
	"Tainted Jacob",
]
